2024-12-13 15:43:50,956 - root - ERROR - Timestamp: 2024-12-13 15:43:50
Exception Type: WrongPasswordError
Context: 자동 대낙 처리 중 오류 발생
Error Details: 비밀번호 오류
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\auto_deanak.py", line 88, in deanak_start
    if self.password_handler.handle_password_screen(screen, loaded_templates, password_list, self.screen_state):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\detection\password_handler.py", line 59, in handle_password_screen
    raise e  # 예외를 발생시켜 상위 코드로 전달
    ^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\detection\password_handler.py", line 49, in handle_password_screen
    raise WrongPasswordError("비밀번호 오류")
src.utils.error_handler.WrongPasswordError: 비밀번호 오류

--------------------------------------------------------------------------------

2024-12-13 17:07:53,468 - root - ERROR - Timestamp: 2024-12-13 17:07:53
Exception Type: NoWorkerError
Context: {'worker_id': None}
Error Details: 해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\do_service.py", line 25, in _validate_worker
    raise NoWorkerError("해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.")
src.utils.error_handler.NoWorkerError: 해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.

--------------------------------------------------------------------------------

2024-12-13 17:10:15,766 - root - ERROR - Timestamp: 2024-12-13 17:10:15
Exception Type: NoWorkerError
Context: {'worker_id': None}
Error Details: 해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\do_service.py", line 25, in _validate_worker
    raise NoWorkerError("해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.")
src.utils.error_handler.NoWorkerError: 해당 worker_id가 remote_pcs테이블에 존재하지 않습니다.

--------------------------------------------------------------------------------

