2024-12-20 11:14:25,095 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<DoService._wait_and_check_timer() running at C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\do_service.py:108> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2024-12-20 16:44:04,223 - root - ERROR - Timestamp: 2024-12-20 16:44:04
Exception Type: CantFindTenMinDataError
Context: {'server_id': 27518, 'deanak_id': 1}
Error Details: 10분접속 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

