2024-12-06 09:54:21,991 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 73, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 09:58:22,424 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 09:58:52,462 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:00:57,600 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:04:33,619 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 10:04:55,578 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:08:19,959 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:16:47,328 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 10:17:14,509 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:19:00,198 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:20:43,134 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 77, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:21:38,491 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 10:24:16,836 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 10:24:42,792 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 15:28:07,404 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 15:43:33,315 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 15:43:54,561 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 15:48:30,225 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "c:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 15:49:01,992 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "c:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 15:51:16,699 - root - ERROR - Error: OTP 텍스트 추출 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 78, in check_otp
    raise Exception("OTP 텍스트 추출 실패")
Exception: OTP 텍스트 추출 실패

2024-12-06 15:54:00,667 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 70, in check_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

2024-12-06 16:12:07,682 - root - ERROR - Error: cannot unpack non-iterable NoneType object
Context: {'worker_id': 'deanak2'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 96, in check_otp
    raise e
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 71, in check_otp
    top_left, bottom_right, _ = self.image_matcher.detect_template(screen, templates["otp_frame"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

2024-12-06 16:40:11,196 - root - ERROR - Error: name 'state' is not defined
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 30, in check_otp
    server_id = await state.unique_id().read_unique_id()
                      ^^^^^
NameError: name 'state' is not defined

2024-12-06 17:32:56,017 - root - ERROR - Error: name 'state' is not defined
Context: {'unique_id_value': 47969}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\app.py", line 37, in cleanup_resources
    await stop_deanak()
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\controller\deanak_controller.py", line 42, in stop_deanak
    return await deanak_service.stop_deanak()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 64, in stop_deanak
    if state.service_running_task:
       ^^^^^
NameError: name 'state' is not defined

2024-12-06 17:46:13,463 - root - ERROR - Error: 'RemoteController' object has no attribute 'press_key'
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 44, in check_otp
    self.remote.press_key(self.remote.REMOTE_TOGGLE_KEY)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RemoteController' object has no attribute 'press_key'

2024-12-06 17:47:34,498 - root - ERROR - Error: 'RemoteController' object has no attribute 'press_key'
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 44, in check_otp
    self.remote.press_key(self.remote.REMOTE_TOGGLE_KEY)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RemoteController' object has no attribute 'press_key'

2024-12-06 17:51:01,033 - root - ERROR - Error: 'RemoteController' object has no attribute 'press_key'
Context: {'worker_id': 'deanak1'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 46, in check_otp
    self.remote.press_key(self.remote.REMOTE_TOGGLE_KEY)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RemoteController' object has no attribute 'press_key'

2024-12-06 17:54:07,550 - root - ERROR - Error: OTP 영역 찾기 실패
Context: {'worker_id': 'deanak2'}
Traceback: Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\deanak_service.py", line 42, in check_otp
    otp_text = await self.otp_service.capture_and_extract_otp()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\otp_service.py", line 62, in capture_and_extract_otp
    return await self._extract_otp(screen, templates)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\otp_service.py", line 48, in _extract_otp
    raise e
  File "C:\Users\gameins\Desktop\auto_deanak_program\auto_deanak\src\service\otp_service.py", line 26, in _extract_otp
    raise Exception("OTP 영역 찾기 실패")
Exception: OTP 영역 찾기 실패

