2024-12-17 17:54:13,108 - root - ERROR - Timestamp: 2024-12-17 17:54:13
Exception Type: TypeError
Context: 작업 실패
Error Details: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 85, in ten_min_start
    await self.remote_pcs_dao.update_tasks_request(db, server_id, "waiting")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 98, in ten_min_start
    await self.remote_pcs_dao.update_tasks_request(db, server_id, "stopped")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'

--------------------------------------------------------------------------------

2024-12-17 18:03:49,436 - root - ERROR - Timestamp: 2024-12-17 18:03:49
Exception Type: CantFindTenMinDataError
Context: {'server_id': 51874, 'deanak_id': 1}
Error Details: auto_ten_min 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------